name: CI
on:
  pull_request:
  push:
env:
  MSRV: "1.70"
jobs:
  check:
    name: Check
    strategy:
      matrix:
        toolchain:
          - MSRV
          - stable
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain == 'MSRV' && env.MSRV || 'stable' }}

      - uses: Swatinem/rust-cache@v2

      - name: Run cargo check
        run: |
          rustc --version
          cargo check

  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, ubuntu-24.04-arm]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install MSRV toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "${{ env.MSRV }}"

      - uses: Swatinem/rust-cache@v2

      - name: Check rust version
        run: rustc --version

      - name: Run cargo test
        run: cargo test

  lints:
    name: Lints
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install MSRV toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "${{ env.MSRV }}"
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v2

      - name: Check rust version
        run: rustc --version

      - name: Run cargo fmt
        run: cargo fmt --check

      - name: Run cargo clippy with default features enabled
        run: cargo clippy -- -D warnings

      - name: Run cargo clippy with all features enabled
        run: cargo clippy --all-features -- -D warnings

      - name: Run cargo doc
        run: cargo doc --no-deps --document-private-items
        env:
          RUSTDOCFLAGS: -D warnings
